@startuml
!theme plain
top to bottom direction
skinparam linetype ortho

class Achievement_Percentages {
   Percentage: float
   appid: int(10) unsigned
   Name: varchar(64)
}
class App_ID_Info {
   Title: varchar(128)
   Type: varchar(128)
   Price: double
   Release_Date: datetime
   Rating: int(11)
   Required_Age: int(11)
   Is_Multiplayer: int(11)
   appid: int(10) unsigned
}
class App_ID_Info_Old {
   Title: varchar(128)
   Type: varchar(128)
   Price: double
   Release_Date: datetime
   Rating: int(11)
   Required_Age: int(11)
   Is_Multiplayer: int(11)
   appid: int(10) unsigned
}
class Friends {
   relationship: varchar(32)
   friend_since: datetime
   dateretrieved: datetime
   LccTag: int(1) unsigned
   steamid_a: bigint(20) unsigned
   steamid_b: bigint(20) unsigned
}
class Games_1 {
   playtime_2weeks: int(10) unsigned
   playtime_forever: int(10) unsigned
   dateretrieved: datetime
   steamid: bigint(20) unsigned
   appid: int(10) unsigned
}
class Games_2 {
   playtime_2weeks: int(10) unsigned
   playtime_forever: int(10) unsigned
   dateretrieved: datetime
   steamid: bigint(20) unsigned
   appid: int(10) unsigned
}
class Games_Daily {
   playtime_2weeks: int(10) unsigned
   playtime_forever: int(10) unsigned
   steamid: bigint(20) unsigned
   appid: int(10) unsigned
   dateretrieved: datetime
}
class Games_Developers {
   appid: int(10) unsigned
   Developer: varchar(64)
}
class Games_Developers_Old {
   appid: int(10) unsigned
   Developer: varchar(64)
}
class Games_Genres {
   appid: int(10) unsigned
   Genre: varchar(64)
}
class Games_Genres_Old {
   appid: int(10) unsigned
   Genre: varchar(64)
}
class Games_Publishers {
   appid: int(10) unsigned
   Publisher: varchar(64)
}
class Games_Publishers_Old {
   appid: int(10) unsigned
   Publisher: varchar(64)
}

class Player_Summaries {
   personaname: varchar(64)
   profileurl: varchar(128)
   avatar: varchar(128)
   avatarmedium: varchar(128)
   avatarfull: varchar(128)
   personastate: tinyint(3) unsigned
   communityvisibilitystate: tinyint(3) unsigned
   profilestate: tinyint(3) unsigned
   lastlogoff: datetime
   commentpermission: tinyint(3) unsigned
   realname: varchar(128)
   primaryclanid: bigint(20) unsigned
   timecreated: datetime
   gameid: int(10) unsigned
   gameserverip: varchar(64)
   gameextrainfo: varchar(64)
   cityid: int(10) unsigned
   loccountrycode: varchar(2)
   locstatecode: varchar(4)
   loccityid: int(10) unsigned
   dateretrieved: datetime
   steamid: bigint(20) unsigned
}
@enduml